---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-demo-project
  namespace: default
  labels:
    app: my-demo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-demo-project
  template:
    metadata:
      labels:
        app: my-demo-project
    spec:
      containers:
      - name: my-demo-project
        image: "sfiratcimen/my-demo-project:latest"
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-demo-project
  namespace: default
spec:
  selector:
    app: my-demo-project
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
